---
# create_a_vimrc/tasks/main.yml

- name: 'Set primary group to users on SUSE/openSUSE'
  ansible.builtin.set_fact:
    primary_group_name: 'users'
  when: '
    ansible_distribution == "SLES" or
    ansible_distribution == "openSUSE Leap" or
    ansible_distribution == "openSUSE MicroOS" or
    ansible_distribution == "openSUSE Tumbleweed"
    '

- name: 'Install package vim-data'
  ansible.builtin.package:
    name: 'vim-data'
  when:
    - '
      ansible_distribution == "Fedora"
      or ansible_distribution == "SLES"
      or ansible_distribution == "openSUSE Leap"
      or ansible_distribution == "openSUSE Tumbleweed"
      '
    - not ansible_pkg_mgr == "atomic_container"

- name: 'Install package vim'
  ansible.builtin.package:
    name: 'vim'
  when:
    - not ansible_pkg_mgr == "atomic_container"
    - ansible_distribution != "openSUSE MicroOS"
    - ansible_distribution != "Debian"

- name: 'Install package vim'
  ansible.builtin.apt:
    name: 'vim'
    update_cache: true
  when:
    - ansible_distribution == "Debian"

#
# currently fails with 'failed to parse zypper xml output: no element found: line 1, column 0'
#
# - name: 'Install package vim and vim-data on openSUSE MicroOS with a reboot'
#   community.general.zypper:
#     name:
#       - 'vim'
#       - 'vim-data'
#     update_cache: false
#   notify:
#     - 'Reboot on openSUSE MicroOS'
#   when:
#     - ansible_distribution == "openSUSE MicroOS"

- name: 'Install package vim and vim-data on openSUSE MicroOS with a reboot'
  ansible.builtin.command:
    cmd: /usr/sbin/transactional-update --non-interactive --continue pkg in vim vim-data
  register: package_install_output
  changed_when:
    - "'zypper: nothing to update' not in package_install_output.stdout"
  notify:
    - 'Reboot on openSUSE MicroOS'
  when:
    - ansible_distribution == "openSUSE MicroOS"

- name: 'Install package vim and vim-data on Fedora CoreOS with a reboot'
  community.general.rpm_ostree_pkg:
    name:
      - 'vim'
      - 'vim-data'
  notify:
    - 'Reboot on CoreOS'
  when:
    - ansible_pkg_mgr == "atomic_container"

- name: 'Create .vimrc for root'
  ansible.builtin.template:
    src: 'vimrc.j2'
    dest: '/root/.vimrc'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - vimrc_for_root | bool

- name: 'Create .vimrc for other users (if any are supplied)'
  ansible.builtin.template:
    src: 'vimrc.j2'
    dest: "/home/{{ item }}/.vimrc"
    owner: "{{ item }}"
    group: "{{ primary_group_name | default(item) }}"
    mode: '0644'
  with_items:
    - "{{ additional_users }}"
  when: 'additional_users is defined'
