---
# create_a_vimrc/tasks/main.yml

- name: 'Set primary group to users on SUSE/openSUSE'
  ansible.builtin.set_fact:
    primary_group_name: 'users'
  when: '
    ansible_distribution == "SLES" or
    ansible_distribution == "openSUSE Leap" or
    ansible_distribution == "openSUSE MicroOS" or
    ansible_distribution == "openSUSE Tumbleweed"
    '

- name: 'Install package vim-data'
  ansible.builtin.package:
    name: 'vim-data'
  when:
    - '
      ansible_distribution == "Fedora"
      or ansible_distribution == "SLES"
      or ansible_distribution == "openSUSE Leap"
      or ansible_distribution == "openSUSE MicroOS"
      or ansible_distribution == "openSUSE Tumbleweed"
      '
    - not ansible_pkg_mgr == "atomic_container"

- name: 'Install package vim'
  ansible.builtin.package:
    name: 'vim'
  when:
    - not ansible_pkg_mgr == "atomic_container"

- name: 'Install package vim and vim-data on Fedora CoreOS'
  community.general.rpm_ostree_pkg:
    name:
      - 'vim'
      - 'vim-data'
  notify:
    - 'Reboot on CoreOS'
  when:
    - ansible_pkg_mgr == "atomic_container"

- name: 'Create .vimrc for root'
  ansible.builtin.template:
    src: 'vimrc.j2'
    dest: '/root/.vimrc'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - vimrc_for_root | bool

- name: 'Create .vimrc for other users (if any are supplied)'
  ansible.builtin.template:
    src: 'vimrc.j2'
    dest: "/home/{{ item }}/.vimrc"
    owner: "{{ item }}"
    group: "{{ primary_group_name | default(item) }}"
    mode: '0644'
  with_items:
    - "{{ additional_users }}"
  when: 'additional_users is defined'
